version: "3"
services:
  fractal-tree:
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      # HTTPS
      - "traefik.http.routers.$ROUTER-https.entrypoints=https"
      - "traefik.http.routers.$ROUTER-https.rule=Host(`$FT_HOST`)"
networks:
  proxy:
    external: true
