apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fractal-tree-src-pvc
  namespace: fractal-tree
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: "fractal-tree-src-pv"
